#pragma once

#define IS_X64 INTPTR_MAX == INT64_MAX
#define IS_X86 INTPTR_MAX == INT32_MAX

#ifdef __linux__
typedef void* HANDLE;
typedef HANDLE HMODULE;

#define PAGE_NOACCESS PROT_NONE
#define PAGE_READONLY PROT_READ
#define PAGE_WRITECOPY PROT_WRITE
#define PAGE_READWRITE PROT_READ | PROT_WRITE
#define PAGE_EXECUTE PROT_EXEC
#define PAGE_EXECUTE_READ PROT_READ | PROT_EXEC
#define PAGE_EXECUTE_READWRITE PROT_READ | PROT_WRITE | PROT_EXEC
#define PAGE_EXECUTE_WRITECOPY PAGE_EXECUTE_READWRITE
#endif